forgejo:
  app:
    environment: production
  image:
    repository: docker.io/forgejo/forgejo
    name: forgejo
    tag: 13.0.3
    pullPolicy: IfNotPresent

fullnameOverride: forgejo-blue
namespaceOverride: development
serviceNameOverride: forgejo-pool