forgejo:
  app:
    environment: production
  image:
    repository: codeberg.org/forgejo/forgejo
    name: forgejo
    tag: 13.0.3

fullnameOverride: forgejo-blue
namespaceOverride: development
serviceNameOverride: forgejo-pool