apiVersion: app/v1
kind: Deployment
metadata:
  name: forgejo-blue
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo-blue
  template:
    metadata:
      labels:
        app: forgejo-blue
    spec:
      containers:
        - name: forgejo
          image: docker.io/forgejo/forgejo:latest
          ports:
            - containerPort: 3000