apiVersion: v1
kind: Service
metadata:
  name: forgejo-blue
  namespace: development
spec:
  selector:
    app: forgejo-blue
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http