apiVersion: v1
kind: Service
metadata:
  name: {{ default "forgejo-blue" .Values.fullnameOverride }}
  # namespace intentionally omitted: ArgoCD / Helm will set destination namespace
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  selector:
    app: {{ default "forgejo-blue" .Values.fullnameOverride }}
  ports:
    - port: {{ default 3000 .Values.service.port }}
      targetPort: {{ default 3000 .Values.service.port }}
      protocol: TCP
      name: http