argo-cd:
  server:
    dnsPolicy: "None"
    dnsConfig:
      nameservers:
        - "8.8.8.8"
        - "1.1.1.1"
      searches:
        - "default.svc.cluster.local"
        - "svc.cluster.local"
        - "cluster.local"
      options:
        - name: "ndots"
          value: "2"
  repoServer:
    dnsPolicy: "None"
    dnsConfig:
      nameservers:
        - "8.8.8.8"
        - "1.1.1.1"
      searches:
        - "default.svc.cluster.local"
        - "svc.cluster.local"
        - "cluster.local"
      options:
        - name: "ndots"
          value: "5"
  applocationSet:
    dnsPolicy: "None"
    dnsConfig:
      nameservers:
        - "8.8.8.8"
        - "1.1.1.1"