apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default "postgres-blue" .Values.fullnameOverride }}
  # namespace intentionally omitted: ArgoCD / Helm will set destination namespace
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ default "postgres-blue" .Values.fullnameOverride }}
  template:
    metadata:
      labels:
        app: {{ default "postgres-blue" .Values.fullnameOverride }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ default 5432 .Values.service.port }}
{{- /* Render env block with correct indentation using printf+nindent to avoid template/indent errors */}}
{{- if .Values.credentials.secret.enabled }}
{{- $s := .Values.credentials.secret.name }}
{{- printf "env:\n  - name: POSTGRES_USER\n    valueFrom:\n      secretKeyRef:\n        name: %s\n        key: POSTGRES_USER\n  - name: POSTGRES_PASSWORD\n    valueFrom:\n      secretKeyRef:\n        name: %s\n        key: POSTGRES_PASSWORD\n  - name: POSTGRES_DB\n    valueFrom:\n      secretKeyRef:\n        name: %s\n        key: POSTGRES_DB\n" $s $s $s | nindent 10 }}
{{- else }}
{{- printf "env:\n  - name: POSTGRES_USER\n    value: \"%s\"\n  - name: POSTGRES_PASSWORD\n    value: \"%s\"\n  - name: POSTGRES_DB\n    value: \"%s\"\n" .Values.postgresql.username .Values.postgresql.password .Values.postgresql.database | nindent 10 }}
{{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ default "postgres-pvc" .Values.fullnameOverride }}
