apiVersion: v1
kind: Service
metadata:
  name: {{ default "postgres-blue" .Values.fullnameOverride }}
  # namespace intentionally omitted: ArgoCD / Helm will set destination namespace
spec:
  selector:
    app: {{ default "postgres-blue" .Values.fullnameOverride }}
  ports:
    - port: {{ default 5432 .Values.service.port }}
      targetPort: {{ default 5432 .Values.service.port }}
      protocol: TCP
      name: postgres

