apiVersion: v1
kind: Service
metadata:
  name: postgres-pool
  namespace: development
spec:
  selector:
    app: postgres-blue
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres

